// Load all the CSS as a raw string (generated by the pre-build script)
import animateCSS from './Animate.css.txt'

// Return all the CSS for this library as a string
export function getCSSString () {
  return animateCSS
}
