// Load all the CSS as a raw string (generated by the pre-build script)
import fontAwesomeCSS from './FontAwesome.css.txt'

// Return all the CSS for this library as a string
export function getCSSString () {
  // Rewrite the internal URLs
  const baseURL = chrome.runtime.getURL('webfonts')
  const adjFontAwesomeCSS = fontAwesomeCSS.replace(/url\(\.\.\/webfonts\/(.+?)\)/g, `url(${baseURL}/$1)`)

  // Return CSS as one long string
  return adjFontAwesomeCSS
}
