// Load all the CSS as a raw string (generated by the pre-build script)
import tippyCSS from './TippyJS.css.txt'

// Return all the CSS for this library as a string
export function getCSSString () {
  return tippyCSS
}
